In [2]:
import requests

from bs4 import BeautifulSoup

liste_regions = ['picardie', 'champagne-ardenne', 'nord-pas-de-calais', 'normandie',
                 'champagne-ardenne', 'poitou-charentes', 'centre', 'bretagne', 'bourgogne',
                 'bretagne', 'normandie', 'centre', 'normandie', 'charentes', 'bretagne',
                 'lorraine', 'bretagne', 'pays-de-la-loire', 'normandie']

liste_ville = ['amiens', 'reims', 'lille', 'rouen', 'troyes', 'poitiers', 'tours',
               'rennes', 'dijon', 'lannion', 'caen', 'bourges', 'alen√ßon', 'saintes',
               'vannes', 'nancy', 'concarneau', 'nantes', 'granville']

In [3]:
liste_id = {'amiens': 226,
 'reims': 177,
 'lille': 210,
 'rouen': 218,
 'troyes': 178,
 'poitiers': 233,
 'tours': 168,
 'rennes': 172,
 'dijon': 170,
 'lannion': 1002,
 'caen': 216,
 'bourges': 163,
 'alencon-orne': 873,
 'saintes-charente-maritime': 5655,
 'vannes': 173,
 'nancy': 200,
 'concarneau': 1043,
 'nantes': 221,
 'granville': 2181}

In [4]:
#for id_ in liste_id.values():
#    url_ville = f"https://www.historique-meteo.net/site/export.php?ville_id={id_}"
#    response = requests.get(url_ville)

In [47]:
import pandas as pd

csv_url = '/Users/pierre/code/PierreCeraH/data-challenges/08-Projects/01/data/raw data/export-cognac.csv'

In [48]:
df = pd.read_csv(csv_url, skiprows=3)

In [49]:
df.shape

(4779, 22)

In [50]:
cols_to_drop = ['TEMPERATURE_MORNING_C', 'TEMPERATURE_NOON_C', 'TEMPERATURE_EVENING_C','VISIBILITY_AVG_KM', 'WEATHER_CODE_MORNING', 'WEATHER_CODE_NOON', 'WEATHER_CODE_EVENING', 'OPINION']
df = df.drop(cols_to_drop, axis=1)
df.shape

(4779, 14)

In [51]:
df.dtypes

DATE                       object
MAX_TEMPERATURE_C           int64
MIN_TEMPERATURE_C           int64
WINDSPEED_MAX_KMH           int64
PRECIP_TOTAL_DAY_MM       float64
HUMIDITY_MAX_PERCENT        int64
PRESSURE_MAX_MB             int64
CLOUDCOVER_AVG_PERCENT    float64
HEATINDEX_MAX_C             int64
DEWPOINT_MAX_C              int64
WINDTEMP_MAX_C              int64
TOTAL_SNOW_MM             float64
UV_INDEX                    int64
SUNHOUR                   float64
dtype: object

In [52]:
df.isna().sum()

DATE                      0
MAX_TEMPERATURE_C         0
MIN_TEMPERATURE_C         0
WINDSPEED_MAX_KMH         0
PRECIP_TOTAL_DAY_MM       0
HUMIDITY_MAX_PERCENT      0
PRESSURE_MAX_MB           0
CLOUDCOVER_AVG_PERCENT    0
HEATINDEX_MAX_C           0
DEWPOINT_MAX_C            0
WINDTEMP_MAX_C            0
TOTAL_SNOW_MM             0
UV_INDEX                  0
SUNHOUR                   0
dtype: int64

In [53]:
df['DATE'] = pd.to_datetime(df['DATE'])

In [55]:
df = df.set_index(['DATE'])

In [58]:
df.resample('W').mean()

,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,PRESSURE_MAX_MB,CLOUDCOVER_AVG_PERCENT,HEATINDEX_MAX_C,DEWPOINT_MAX_C,WINDTEMP_MAX_C,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR
DATE,,,,,,,,,,,,,
2009-01-04,6.000000,0.500000,18.250000,0.000000,71.250000,1022.250000,23.718750,6.000000,1.250000,-4.000000,0.0,2.000000,8.250000
2009-01-11,3.000000,-3.142857,17.285714,0.157143,78.571429,1024.571429,21.696429,3.142857,0.714286,-8.000000,0.1,1.857143,8.185714
2009-01-18,7.714286,2.714286,18.857143,2.942857,95.142857,1020.857143,51.660714,7.714286,5.285714,-1.000000,0.0,1.857143,5.928571
2009-01-25,9.571429,6.428571,32.857143,16.542857,93.428571,1004.857143,69.196429,9.571429,7.857143,1.857143,0.0,2.428571,5.214286
2009-02-01,10.142857,3.857143,14.714286,2.014286,93.285714,1011.571429,43.696429,10.142857,6.428571,1.142857,0.0,2.285714,8.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-09,11.428571,6.285714,23.571429,0.657143,87.857143,1024.000000,57.714286,11.428571,6.857143,3.571429,0.0,2.428571,6.657143
2022-01-16,9.428571,1.857143,13.285714,0.242857,80.857143,1032.714286,18.517857,9.428571,3.000000,-1.142857,0.0,2.000000,7.942857
2022-01-23,9.571429,1.714286,18.428571,0.057143,91.000000,1035.142857,20.892857,9.571429,5.142857,-1.428571,0.0,2.285714,8.442857
2022-01-30,11.428571,2.428571,10.857143,0.000000,88.000000,1035.142857,14.875000,11.428571,5.285714,-0.428571,0.0,3.000000,8.842857
2022-02-06,10.000000,8.000000,26.000000,0.100000,98.000000,1032.000000,73.500000,10.000000,8.000000,5.000000,0.0,2.000000,9.800000