In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
filepath = '/Users/pierre/code/PierreCeraH/deepagri/raw_data/cleaned/Histo_data_YieldsAreasProd.xlsx'

df = pd.read_excel(filepath)
df = df.rename(columns={'Unnamed: 0':'ANNEE'})

df

,ANNEE,AIN,AIN.1,AIN.2,AISNE,AISNE.1,AISNE.2,ALLIER,ALLIER.1,ALLIER.2,...,SEINE ST DENIS.2,VAL DE MARNE,VAL DE MARNE.1,VAL DE MARNE.2,VAL D'OISE,VAL D'OISE.1,VAL D'OISE.2,TOTAL,TOTAL.1,TOTAL.2
0,Ann√©e,Suf.(ha),Rend(q/ha),Prod.(t),Suf.(ha),Rend(q/ha),Prod.(t),Suf.(ha),Rend(q/ha),Prod.(t),...,Prod.(t),Suf.(ha),Rend(q/ha),Prod.(t),Suf.(ha),Rend(q/ha),Prod.(t),Suf.(ha),Prod.(t),Rend(q/ha)
1,2000,27500,74,203500,184400,82.902386,1528720,47137,68,320531.6,...,3612,379,80,3032,25450,80,203600,4910142,35667737.1,72.640948
2,2001,28008,60,168048,167033,81.928445,1368475.4,45134,54,243723.6,...,3151.2,322,75,2415,22465,77,172980.5,4457702,30174697.3,67.69115
3,2002,29017,73,211824.1,174069,84.931544,1478394.9,44021,62,272930.2,...,3224,404,81,3272.4,25604,83,212513.2,4888878,37276484.8,76.247525
4,2003,24021,53,127311.3,172102,75,1290765,42031,45,189139.5,...,3330,399,62,2473.8,24878,68,169170.4,4513832,28993238.3,64.231984
5,2004,28533,80,228264,175589,91.904635,1613744.3,46000,66,303600,...,3349.5,429,74,3174.6,25248,84,212083.2,4818995,37524039.8,77.866941
6,2005,27039,68,183865.2,178097,80.884209,1440523.5,44000,59,259600,...,3353.8,406,82,3329.2,26088,80,208704,4841253,34748270,71.775365
7,2006,31555,72,227196,177751,79.944979,1421030,44200,60,265200,...,3440,420,80,3360,25402,75,190515,4778563,33159950.3,69.393142
8,2007,32065,62,198803,175688,75.994718,1335136,43000,51,219300,...,3040,405,76,3078,24766,76,188221.6,4766876,30666411.5,64.332304
9,2008,32075,63,202072.5,184688,84.99686,1569790,45600,56,255360,...,2905,429,83,3560.7,25839,83,214463.7,5044853,36757936.5,72.862255
10,2009,27140,69.712601,189200,173633,89.977942,1562314,42700,68,290360,...,3711.3,464,83,3851.2,25046,89,222909.4,4711546,36069496.1,76.555543
11,2010,33300,71.964054,239640.3,177466,83.68559,1485134.7,47300,65,307450,...,2924,470,76,3572,24101,85,204858.5,4898515,35486640.3,72.44367
12,2011,32500,69.815385,226900,186550,81.986695,1529461.8,46300,53,245390,...,3063.6,497,67,3329.9,25745,74,190513,4990178,33970210.5,68.074146
13,2012,34200,66.964912,229020,182476,81.241358,1482459.8,48200,65,313300,...,3017.6,445,82,3649,25715,82,210863,4860633,35502941.4,73.041806
14,2013,33755,61.973337,209191,185560,90.976374,1688157.6,48800,64,312320,...,3366,538,83,4465.4,24645,85,209482.5,4983661,36870814.5,73.983392
15,2014,30030,71.858475,215791,188500,92.959151,1752280,48250,64.854922,312925,...,2614.5,535,85,4547.5,25520,83,211816,5010456,37466078.2,74.775785
16,2015,33780,71.909414,242910,188874,94.964341,1793629.5,49500,61.911111,306460,...,3094,505,83,4191.5,25225,91,229547.5,5161387,40944642.4,79.328759
17,2016,37570,54.972052,206530,185720,52.996446,984250,54540,51.991199,283560,...,1950,465,45,2092.5,24710,50,123550,5131791,27560667.8,53.705749
18,2017,32370,73.969725,239440,182000,83.998352,1528770,50000,60.459,302295,...,2747,430,75,3225,24290,82,199178,4962079,36559140.5,73.677063
19,2018,34665,66.993509,232233,179130,82,1468866,48400,59.958678,290200,...,2733.5,390,75,2925,23030,77,177331,4880208,34045411.9,69.762215
20,2019,34489,78.971179,272363.7,184980,92,1701816,49720,56.95897,283200,...,3476,460,87,4002,23455,88,206404,4998750,39516461.6,79.052686
21,2020,28050,63.805348,178974,169260,83.982039,1421480,47500,49.915789,237100,...,2535,285,72,2052,21220,78,165516,4260925,29177401.3,68.476684
22,2021,37440,68.981838,258268,191420,82.002717,1569696,49410,57.935236,286258,...,2739,430,81,3483,23870,83,198121,4973631,35409386.8,71.194238
23,2022,35000,0,0,190900,0,0,48400,0,0,...,0,415,0,0,23865,0,0,4923970,0,0

In [ ]:
df = df.loc[1:,:]
df = df.set_index('ANNEE')

cols = df.columns
cols_to_drop = []
for col in cols :
    if '1' in col:
        cols_to_drop.append(col)
    elif '2' in col:
        cols_to_drop.append(col)

df = df.drop(cols_to_drop, axis=1)
df = df.rename(columns={'TOTAL':'FRANCE'})

df_surfaces_France = df[['FRANCE']]

df = df.drop('FRANCE', axis=1)
df = df.loc[2010:,:]

cols = df.columns
dict_col_to_rename = {}
i=1
for col in cols :
    dict_col_to_rename[col]=i
    i = i+1
df = df.rename(columns=dict_col_to_rename)

dept_to_keep = [80,51,59,76,10,86,37,35,21,22,14,18,61,17,56,54,29,44,50,63,67,31,68,26,12,43,87,69,46,9,33,65,40,5,34,13,83,66]
cols_to_drop = []

for i in range(1,96):
    if i not in dept_to_keep :
        cols_to_drop.append(i)
df = df.drop(columns=cols_to_drop)

df_surfaces = pd.DataFrame(df.stack())

df_surfaces = df_surfaces.rename(columns={0:'Production'})
df_surfaces = df_surfaces.reset_index()
df_surfaces['Ind']=df_surfaces['ANNEE'].astype(str)+'-'+df_surfaces['level_1'].astype(str)

df_surfaces = df_surfaces.drop(['level_1','ANNEE'], axis=1)
df_surfaces = df_surfaces.set_index('Ind')

In [34]:
df_surfaces

        Production
Ind
2010-5        2379
2010-9        7050
2010-10     113145
2010-12      11150
2010-13        375
...            ...
2022-76     115650
2022-80     195100
2022-83        445
2022-86     135000
2022-87      12600

[494 rows x 1 columns]