In [ ]:
liste_ville =['amiens','reims','lille','rouen','troyes','poitiers','tours','rennes','dijon','lannion','caen',
              'bourges','alençon','saintes','vannes','nancy','concarneau','nantes','granville',
              'clermont-ferrand','Strasbourg','toulouse','colmar','valence','rodez-aveyron',
              'puy-en-velay-haute-loire','Limoges','lyon','Cahors-lot','foix-ariege','bordeaux',
              'tarbes','mont-de-marsan','gap-hautes-alpes','Montpellier','Marseille','Toulon','Perpignan']

In [2]:
import pandas as pd

In [5]:
filepath = 'https://raw.githubusercontent.com/PierreCeraH/deepagri/5d081b5a3fb2185e861d8f37f9bbeb2d88d8bbfe/deepagri/data/Production_Y.csv'
df = pd.read_csv(filepath)
df.drop('Unnamed: 0',axis=1,inplace=True)
df = df.drop('Prod.(t)',axis=1)
df.set_index('Année',inplace=True)
df = df.T
df = df.reset_index()
df

Année,index,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1,203500.0,168048.0,211824.1,127311.3,228264.0,183865.2,227196.0,198803.0,202072.5,...,229020.0,209191.0,215791.0,242910.0,206530.0,239440.0,232233.0,272363.7,178974.0,258268.0
1,2,1528720.0,1368475.4,1478394.9,1290765.0,1613744.3,1440523.5,1421030.0,1335136.0,1569790.0,...,1482459.8,1688157.6,1752280.0,1793629.5,984250.0,1528770.0,1468866.0,1701816.0,1421480.0,1569696.0
2,3,320531.6,243723.6,272930.2,189139.5,303600.0,259600.0,265200.0,219300.0,255360.0,...,313300.0,312320.0,312925.0,306460.0,283560.0,302295.0,290200.0,283200.0,237100.0,286258.0
3,4,8750.0,5728.3,5684.0,3725.2,3814.2,4082.0,4600.4,7207.2,7884.0,...,10623.0,11804.6,11151.0,9727.0,9424.7,7418.0,5801.0,7866.2,8982.0,15417.3
4,5,12630.0,11270.5,14084.0,9415.7,8874.9,6581.8,6769.5,7848.0,8744.0,...,10910.0,11611.0,13523.5,15085.7,14586.1,10899.0,7499.0,10403.5,9612.0,12160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,91,319200.0,268294.0,312641.4,232119.6,312362.2,282619.5,250140.0,276548.8,289487.4,...,276258.0,286557.5,292485.0,286184.0,150885.0,243675.0,233850.0,265654.5,191952.0,243243.0
91,92,16.0,16.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92,93,3612.0,3151.2,3224.0,3330.0,3349.5,3353.8,3440.0,3040.0,2905.0,...,3017.6,3366.0,2614.5,3094.0,1950.0,2747.0,2733.5,3476.0,2535.0,2739.0
93,94,3032.0,2415.0,3272.4,2473.8,3174.6,3329.2,3360.0,3078.0,3560.7,...,3649.0,4465.4,4547.5,4191.5,2092.5,3225.0,2925.0,4002.0,2052.0,3483.0
94,95,203600.0,172980.5,212513.2,169170.4,212083.2,208704.0,190515.0,188221.6,214463.7,...,210863.0,209482.5,211816.0,229547.5,123550.0,199178.0,177331.0,206404.0,165516.0,198121.0

In [6]:
df.dtypes

Année
index     object
2000     float64
2001     float64
2002     float64
2003     float64
2004     float64
2005     float64
2006     float64
2007     float64
2008     float64
2009     float64
2010     float64
2011     float64
2012     float64
2013     float64
2014     float64
2015     float64
2016     float64
2017     float64
2018     float64
2019     float64
2020     float64
2021     float64
dtype: object

In [9]:
num_dept = list(df['index'])

In [11]:
num_dept

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95']

In [12]:
liste_noms_dept = ['01 - Ain','02 - Aisne','03 - Allier','04 - Alpes-de-Haute-Provence',
                   '05 - Hautes-Alpes','06 - Alpes-Maritimes','07 - Ardèche','08 - Ardennes',
                   '09 - Ariège','10 - Aube','11 - Aude','12 - Aveyron',
                   '13 - Bouches-du-Rhône','14 - Calvados','15 - Cantal','16 - Charente',
                   '17 - Charente-Maritime','18 - Cher','19 - Corrèze',
                   "21 - Côte-d'Or","22 - Côtes-d'Armor","23 - Creuse","24 - Dordogne",
                   "25 - Doubs","26 - Drôme","27 - Eure","28 - Eure-et-Loir",
                   "29 - Finistère","30 - Gard","31 - Haute-Garonne","32 - Gers",
                   "33 - Gironde","34 - Hérault","35 - Ille-et-Vilaine","36 - Indre",
                   "37 - Indre-et-Loire","38 - Isère","39 - Jura","40 - Landes",
                   "41 - Loir-et-Cher","42 - Loire","43 - Haute-Loire","44 - Loire-Atlantique",
                   "45 - Loiret","46 - Lot","47 - Lot-et-Garonne","48 - Lozère",
                   "49 - Maine-et-Loire","50 - Manche","51 - Marne","52 - Haute-Marne",
                   "53 - Mayenne","54 - Meurthe-et-Moselle","55 - Meuse","56 - Morbihan",
                   "57 - Moselle","58 - Nièvre","59 - Nord","60 - Oise",
                   "61 - Orne","62 - Pas-de-Calais","63 - Puy-de-Dôme","64 - Pyrénées-Atlantiques",
                   "65 - Hautes-Pyrénées","66 - Pyrénées-Orientales","67 - Bas-Rhin","68 - Haut-Rhin",
                   "69 - Rhône","70 - Haute-Saône","71 - Saône-et-Loire","72 - Sarthe",
                   "73 - Savoie","74 - Haute-Savoie","76 - Seine-Maritime","77 - Seine-et-Marne",
                   "79 - Deux-Sèvres","80 - Somme","81 - Tarn","82 - Tarn-et-Garonne",
                   "83 - Var","84 - Vaucluse","85 - Vendée","86 - Vienne",
                   "87 - Haute-Vienne","88 - Vosges","89 - Yonne","90 - Territoire de Belfort",
                   "91 - Essonne","92 - Hauts-de-Seine","93 - Seine-Saint-Denis","94 - Val-de-Marne",
                   "95 - Val-d'Oise"]

In [2]:
import pandas as pd
filepath = 'https://raw.githubusercontent.com/PierreCeraH/deepagri/5d081b5a3fb2185e861d8f37f9bbeb2d88d8bbfe/deepagri/data/Production_Y.csv'
df = pd.read_csv(filepath)
df.drop('Unnamed: 0',axis=1,inplace=True)
df = df.drop('Prod.(t)',axis=1)
df.set_index('Année',inplace=True)
df = df.T
df = df.reset_index()

In [3]:
df

Année,index,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1,203500.0,168048.0,211824.1,127311.3,228264.0,183865.2,227196.0,198803.0,202072.5,...,229020.0,209191.0,215791.0,242910.0,206530.0,239440.0,232233.0,272363.7,178974.0,258268.0
1,2,1528720.0,1368475.4,1478394.9,1290765.0,1613744.3,1440523.5,1421030.0,1335136.0,1569790.0,...,1482459.8,1688157.6,1752280.0,1793629.5,984250.0,1528770.0,1468866.0,1701816.0,1421480.0,1569696.0
2,3,320531.6,243723.6,272930.2,189139.5,303600.0,259600.0,265200.0,219300.0,255360.0,...,313300.0,312320.0,312925.0,306460.0,283560.0,302295.0,290200.0,283200.0,237100.0,286258.0
3,4,8750.0,5728.3,5684.0,3725.2,3814.2,4082.0,4600.4,7207.2,7884.0,...,10623.0,11804.6,11151.0,9727.0,9424.7,7418.0,5801.0,7866.2,8982.0,15417.3
4,5,12630.0,11270.5,14084.0,9415.7,8874.9,6581.8,6769.5,7848.0,8744.0,...,10910.0,11611.0,13523.5,15085.7,14586.1,10899.0,7499.0,10403.5,9612.0,12160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,91,319200.0,268294.0,312641.4,232119.6,312362.2,282619.5,250140.0,276548.8,289487.4,...,276258.0,286557.5,292485.0,286184.0,150885.0,243675.0,233850.0,265654.5,191952.0,243243.0
91,92,16.0,16.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92,93,3612.0,3151.2,3224.0,3330.0,3349.5,3353.8,3440.0,3040.0,2905.0,...,3017.6,3366.0,2614.5,3094.0,1950.0,2747.0,2733.5,3476.0,2535.0,2739.0
93,94,3032.0,2415.0,3272.4,2473.8,3174.6,3329.2,3360.0,3078.0,3560.7,...,3649.0,4465.4,4547.5,4191.5,2092.5,3225.0,2925.0,4002.0,2052.0,3483.0
94,95,203600.0,172980.5,212513.2,169170.4,212083.2,208704.0,190515.0,188221.6,214463.7,...,210863.0,209482.5,211816.0,229547.5,123550.0,199178.0,177331.0,206404.0,165516.0,198121.0

In [4]:
#df_graph_dept = df[['index',f'Var {year}-{year-1}']]
df_graph_dept = df.copy()
df_graph_dept['index']=df_graph_dept['index'].astype(str)
df_graph_dept = df_graph_dept.dropna()
df_graph_dept

Année,index,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1,203500.0,168048.0,211824.1,127311.3,228264.0,183865.2,227196.0,198803.0,202072.5,...,229020.0,209191.0,215791.0,242910.0,206530.0,239440.0,232233.0,272363.7,178974.0,258268.0
1,2,1528720.0,1368475.4,1478394.9,1290765.0,1613744.3,1440523.5,1421030.0,1335136.0,1569790.0,...,1482459.8,1688157.6,1752280.0,1793629.5,984250.0,1528770.0,1468866.0,1701816.0,1421480.0,1569696.0
2,3,320531.6,243723.6,272930.2,189139.5,303600.0,259600.0,265200.0,219300.0,255360.0,...,313300.0,312320.0,312925.0,306460.0,283560.0,302295.0,290200.0,283200.0,237100.0,286258.0
3,4,8750.0,5728.3,5684.0,3725.2,3814.2,4082.0,4600.4,7207.2,7884.0,...,10623.0,11804.6,11151.0,9727.0,9424.7,7418.0,5801.0,7866.2,8982.0,15417.3
4,5,12630.0,11270.5,14084.0,9415.7,8874.9,6581.8,6769.5,7848.0,8744.0,...,10910.0,11611.0,13523.5,15085.7,14586.1,10899.0,7499.0,10403.5,9612.0,12160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,91,319200.0,268294.0,312641.4,232119.6,312362.2,282619.5,250140.0,276548.8,289487.4,...,276258.0,286557.5,292485.0,286184.0,150885.0,243675.0,233850.0,265654.5,191952.0,243243.0
91,92,16.0,16.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92,93,3612.0,3151.2,3224.0,3330.0,3349.5,3353.8,3440.0,3040.0,2905.0,...,3017.6,3366.0,2614.5,3094.0,1950.0,2747.0,2733.5,3476.0,2535.0,2739.0
93,94,3032.0,2415.0,3272.4,2473.8,3174.6,3329.2,3360.0,3078.0,3560.7,...,3649.0,4465.4,4547.5,4191.5,2092.5,3225.0,2925.0,4002.0,2052.0,3483.0
94,95,203600.0,172980.5,212513.2,169170.4,212083.2,208704.0,190515.0,188221.6,214463.7,...,210863.0,209482.5,211816.0,229547.5,123550.0,199178.0,177331.0,206404.0,165516.0,198121.0

In [5]:
for i in range(0,9):
    df_graph_dept['index'][i]= '0' + df_graph_dept['index'][i]
df_graph_dept

/var/folders/r9/qs0wyhwx3bd8rswjkrfqczgm0000gn/T/ipykernel_24321/2753491370.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_graph_dept['index'][i]= '0' + df_graph_dept['index'][i]

Année,index,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,01,203500.0,168048.0,211824.1,127311.3,228264.0,183865.2,227196.0,198803.0,202072.5,...,229020.0,209191.0,215791.0,242910.0,206530.0,239440.0,232233.0,272363.7,178974.0,258268.0
1,02,1528720.0,1368475.4,1478394.9,1290765.0,1613744.3,1440523.5,1421030.0,1335136.0,1569790.0,...,1482459.8,1688157.6,1752280.0,1793629.5,984250.0,1528770.0,1468866.0,1701816.0,1421480.0,1569696.0
2,03,320531.6,243723.6,272930.2,189139.5,303600.0,259600.0,265200.0,219300.0,255360.0,...,313300.0,312320.0,312925.0,306460.0,283560.0,302295.0,290200.0,283200.0,237100.0,286258.0
3,04,8750.0,5728.3,5684.0,3725.2,3814.2,4082.0,4600.4,7207.2,7884.0,...,10623.0,11804.6,11151.0,9727.0,9424.7,7418.0,5801.0,7866.2,8982.0,15417.3
4,05,12630.0,11270.5,14084.0,9415.7,8874.9,6581.8,6769.5,7848.0,8744.0,...,10910.0,11611.0,13523.5,15085.7,14586.1,10899.0,7499.0,10403.5,9612.0,12160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,91,319200.0,268294.0,312641.4,232119.6,312362.2,282619.5,250140.0,276548.8,289487.4,...,276258.0,286557.5,292485.0,286184.0,150885.0,243675.0,233850.0,265654.5,191952.0,243243.0
91,92,16.0,16.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92,93,3612.0,3151.2,3224.0,3330.0,3349.5,3353.8,3440.0,3040.0,2905.0,...,3017.6,3366.0,2614.5,3094.0,1950.0,2747.0,2733.5,3476.0,2535.0,2739.0
93,94,3032.0,2415.0,3272.4,2473.8,3174.6,3329.2,3360.0,3078.0,3560.7,...,3649.0,4465.4,4547.5,4191.5,2092.5,3225.0,2925.0,4002.0,2052.0,3483.0
94,95,203600.0,172980.5,212513.2,169170.4,212083.2,208704.0,190515.0,188221.6,214463.7,...,210863.0,209482.5,211816.0,229547.5,123550.0,199178.0,177331.0,206404.0,165516.0,198121.0

In [6]:
df_graph_dept.set_index('index',inplace=True)

In [11]:
df_graph_dept.loc['02',:]

Année
2000    1528720.0
2001    1368475.4
2002    1478394.9
2003    1290765.0
2004    1613744.3
2005    1440523.5
2006    1421030.0
2007    1335136.0
2008    1569790.0
2009    1562314.0
2010    1485134.7
2011    1529461.8
2012    1482459.8
2013    1688157.6
2014    1752280.0
2015    1793629.5
2016     984250.0
2017    1528770.0
2018    1468866.0
2019    1701816.0
2020    1421480.0
2021    1569696.0
Name: 02, dtype: float64